INSERT INTO `loowei_config` VALUES ('site_name', 'Loowei笑话程序');
INSERT INTO `loowei_config` VALUES ('site_url', 'http://www.xiaohua.com');
INSERT INTO `loowei_config` VALUES ('site_logo', 'http://www.xiaohua.com/Public/logo.jpg');
INSERT INTO `loowei_config` VALUES ('site_status', '1');
INSERT INTO `loowei_config` VALUES ('sys_version', 'v2.0.7 Released 20140814');
INSERT INTO `loowei_config` VALUES ('site_html', '0');
INSERT INTO `loowei_config` VALUES ('default_theme', 'default');
INSERT INTO `loowei_config` VALUES ('upload_pic_width', '580');
INSERT INTO `loowei_config` VALUES ('upload_pic_height', '10000');
INSERT INTO `loowei_config` VALUES ('upload_pic_max_size', '2');
INSERT INTO `loowei_config` VALUES ('article_below', '5');
INSERT INTO `loowei_config` VALUES ('article_upper', '1');
INSERT INTO `loowei_config` VALUES ('other_qzone_url', '');
INSERT INTO `loowei_config` VALUES ('collect_upper_min', '150');
INSERT INTO `loowei_config` VALUES ('collect_upper_max', '800');
INSERT INTO `loowei_config` VALUES ('collect_below_min', '150');
INSERT INTO `loowei_config` VALUES ('collect_below_max', '800');
INSERT INTO `loowei_config` VALUES ('sys_key', 'no_key');
INSERT INTO `loowei_config` VALUES ('site_email', 'loowei@loowei.com');
INSERT INTO `loowei_config` VALUES ('seo_title', 'Loowei笑话程序，每天让你笑一百次！');
INSERT INTO `loowei_config` VALUES ('seo_keywords', '糗事，搞笑视频，搞笑图片，笑话，暴笑笑话，Loowei笑话程序');
INSERT INTO `loowei_config` VALUES ('seo_description', 'Loowei笑话程序，每天让你笑一百次！');
INSERT INTO `loowei_config` VALUES ('page_rows', '20');
INSERT INTO `loowei_config` VALUES ('site_icp', '太阳系12345678');
INSERT INTO `loowei_config` VALUES ('site_footer', '<a href="/sitemap_baidu.xml">百度地图</a>\r\n<a href="/sitemap.xml">网站地图</a>\r\n<a href="/rss.xml">RSS订阅</a>\r\n<script type="text/javascript">var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cscript src=''" + _bdhmProtocol + "hm.baidu.com/h.js%3F19b6d084c0cf20a1ef26f87bd9c77199'' type=''text/javascript''%3E%3C/script%3E"));</script>\r\n<!-- Baidu Button BEGIN -->\r\n<script type="text/javascript" id="bdshare_js" data="type=tools&uid=681076" ></script><script type="text/javascript" id="bdshell_js"></script><script type="text/javascript">document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + Math.ceil(new Date()/3600000);</script>\r\n<!-- Baidu Button END -->');
INSERT INTO `loowei_config` VALUES ('TMPL_CACHE_ON', '0');
INSERT INTO `loowei_config` VALUES ('site_waterfall', '1');
INSERT INTO `loowei_config` VALUES ('waterfall_rows', '10');
INSERT INTO `loowei_config` VALUES ('HTML_CACHE_ON', '0');
INSERT INTO `loowei_config` VALUES ('HTML_CACHE_TIME', '60');
INSERT INTO `loowei_config` VALUES ('TMPL_STRIP_SPACE', '1');
INSERT INTO `loowei_config` VALUES ('user_register', '1');
INSERT INTO `loowei_config` VALUES ('user_emailcheck', '0');
INSERT INTO `loowei_config` VALUES ('user_emailchecktpl', ' 欢迎您注册成为{sitename}的用户，您的账号需要邮箱认证，点击下面链接或者将网址复制到浏览器进行认证：{url}');
INSERT INTO `loowei_config` VALUES ('user_getpwdemaitpl', '亲爱的用户{username}，您的账号正在找回密码，点击下面链接或者将网址复制到浏览器进行认证：{url}');
INSERT INTO `loowei_config` VALUES ('open_water', '1');
INSERT INTO `loowei_config` VALUES ('water_file', './Public/water.png');
INSERT INTO `loowei_config` VALUES ('mail_server', '');
INSERT INTO `loowei_config` VALUES ('mail_port', '');
INSERT INTO `loowei_config` VALUES ('mail_from', '');
INSERT INTO `loowei_config` VALUES ('mail_auth', '1');
INSERT INTO `loowei_config` VALUES ('mail_user', '');
INSERT INTO `loowei_config` VALUES ('mail_pwd', '');
INSERT INTO `loowei_config` VALUES ('other_sina_url', 'http://weibo.com/loowei');
INSERT INTO `loowei_config` VALUES ('other_tqq_url', 'http://t.qq.com/loowei');
INSERT INTO `loowei_config` VALUES ('other_feed_url', 'http://feed.feedsky.com/loowei');
INSERT INTO `loowei_config` VALUES ('open_mobile', '0');
INSERT INTO `loowei_config` VALUES ('mobile_site_url', '');
INSERT INTO `loowei_config` VALUES ('open_qq_connect', '0');
INSERT INTO `loowei_config` VALUES ('qq_appid', '');
INSERT INTO `loowei_config` VALUES ('qq_appkey', '');
INSERT INTO `loowei_config` VALUES ('article_below', '5');
INSERT INTO `loowei_config` VALUES ('article_upper', '1');
INSERT INTO `loowei_config` VALUES ('open_sina_connect', '0');
INSERT INTO `loowei_config` VALUES ('sina_appid', '');
INSERT INTO `loowei_config` VALUES ('sina_appkey', '');
INSERT INTO `loowei_config` VALUES ('site_safecode', 'a9fe58c38a5fabaafc6c3af528e183d3');
INSERT INTO `loowei_config` VALUES ('site_create_time', '1373590603');

INSERT INTO `loowei_flink` VALUES (1, '乐维', '乐维互联网应用系统开发商', 'http://www.loowei.com', 1, 1);

INSERT INTO `loowei_adver` VALUES (1, '右侧广告_主题描述_1', '<script type="text/javascript">alimama_pid="mm_33926631_3494525_11419755";alimama_width=300;alimama_height=250; </script> \r\n<script src="http://a.alimama.cn/inf.js" type="text/javascript"></script>', 1373036084, 0, 1);
INSERT INTO `loowei_adver` VALUES (2, '右侧广告_主题描述_2', '<script type="text/javascript"><!--\r\n							google_ad_client = "ca-pub-5720404822966052";\r\n							/* 学校右侧广告 */\r\n							google_ad_slot = "6767190082";\r\n							google_ad_width = 300;\r\n							google_ad_height = 250;\r\n							//-->\r\n						</script>\r\n						<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>', 1373036803, 0, 1);
INSERT INTO `loowei_adver` VALUES (3, '右侧广告_主题描述_3', '<script type="text/javascript"><!--\r\n							google_ad_client = "ca-pub-5720404822966052";\r\n							/* 学校右侧2 */\r\n							google_ad_slot = "3518698880";\r\n							google_ad_width = 300;\r\n							google_ad_height = 250;\r\n							//-->\r\n						</script>\r\n						<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>', 1373036822, 0, 1);
INSERT INTO `loowei_adver` VALUES (4, '右侧广告_主题描述_4', '<script type="text/javascript"> \r\n									alimama_pid="mm_33926631_3494525_11419773"; \r\n									alimama_width=300; \r\n									alimama_height=250; \r\n								</script> \r\n								<script src="http://a.alimama.cn/inf.js" type="text/javascript"></script>	', 1373036832, 0, 1);
INSERT INTO `loowei_adver` VALUES (5, '右侧广告_主题描述_5', '<script type="text/javascript"><!--\r\n									google_ad_client = "ca-pub-5720404822966052";\r\n									/* 学校右侧3 */\r\n									google_ad_slot = "9020175684";\r\n									google_ad_width = 300;\r\n									google_ad_height = 250;\r\n									//-->\r\n									</script>\r\n									<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>', 1373036849, 0, 1);
INSERT INTO `loowei_adver` VALUES (6, '右侧广告_主题描述_6', '<script type="text/javascript"><!--\r\n						google_ad_client = "ca-pub-5720404822966052";\r\n						/* 468横幅 */\r\n						google_ad_slot = "1688712080";\r\n						google_ad_width = 468;\r\n						google_ad_height = 15;\r\n						//-->\r\n					</script>\r\n					<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>', 1373037555, 0, 1);

INSERT INTO `loowei_hot_tag` VALUES (1, '伤不起', 1, 1);
INSERT INTO `loowei_hot_tag` VALUES (2, '二奶', 2, 1);
INSERT INTO `loowei_hot_tag` VALUES (3, '围观', 3, 1);
INSERT INTO `loowei_hot_tag` VALUES (4, 'gg', 4, 1);
INSERT INTO `loowei_hot_tag` VALUES (5, 'ml', 5, 1);
INSERT INTO `loowei_hot_tag` VALUES (6, '小三', 6, 1);
INSERT INTO `loowei_hot_tag` VALUES (7, '正太', 10, 1);